name: AndroidRelease

on: push

jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'release build')"
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Get VersionName
      run: |
        export versionName=$(./gradlew -q getVersionName)
        echo "::set-env name=versionName::$versionName"
    - name: Echo VersionName
      run: echo "app-release-{{$versionName}}.apk"
